### ISSUE TITLE
Broken in server version 15

### ISSUE THREAD

**Issue by detly** [nextcloud/privatedata#2]
![pda](https://user-images.githubusercontent.com/311239/55315214-9958e900-54b7-11e9-91a3-ed7e25735893.png)

After upgrading to 15.0.5:

> This app cannot be installed because the following dependencies are not fulfilled:
> Server version 14 or lower is required.

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Released: https://apps.nextcloud.com/apps/privatedata
